version: 2

sources:
  - name: postgres-dbt-raw
    tables:
      - name: public.silver_calendar
      - name: public.silver_reviews
      - name: public.silver_listings

models:
  - name: tb_availability_date
    description: "Availability variation per day"
    columns:
      - name: date
        description: "Date"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: total_available
        description: "Total available places"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          # - dbt_expectations.expect_column_values_to_be_of_type:
          #     column_type: numeric
      - name: percent_available
        description: "Percentage of total available places"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          # - dbt_expectations.expect_column_values_to_be_of_type:
          #     column_type: numeric

  - name: tb_mean_price_date
    description: "Mean price of each day"
    columns:
      - name: date
        description: "Date"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: mean_price
        description: "Mean price of that date"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
      - name: mean_adjusted_price
        description: "Mean adjusted price of that date"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          # - dbt_expectations.expect_table_column_count_to_be_between:
          #     min_value: 0
          #     max_value: 100000000000000

  - name: tb_mean_neighbourhood
    description: "Availability variation per neighbourhood"
    columns:
      - name: neighbourhood
        description: "Date"
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: text
      - name: mean_price
        description: "Mean price of that neighbourhood"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: mean_accommodates
        description: "Mean accommodate available"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: mean_bedrooms
        description: "Mean bedrooms available"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: mean_beds
        description: "Mean beds available"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
